version: "3.8"
services:
    backend:
        container_name: django_js_backend
        image: django_js:1.0.1
        build: .
        tty: true
        ports:
            - 8001:8000
        volumes:
            - .:/home/django_js
        restart: unless-stopped
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
    db:
        image: postgres:15.1 # mysql:8.0.32
        container_name: djs_postgres_db
        volumes:
            - ./data/postgres/db:/var/lib/postgresql/data # - ./data/mysql/db:/var/lib/mysql
        environment:
            POSTGRES_DB: ${DB_NAME:?error} # abort if not set or empty
            POSTGRES_USER: ${DB_USER:?error}
            POSTGRES_PASSWORD: ${DB_PASSWORD?error} # abort if not set, proceed if empty ''
            # MYSQL_ALLOW_EMPTY_PASSWORD: "true" # not advised in prod only for testing
            # MYSQL_DATABASE: "${DB_NAME:?error}" # must set or error
            # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:?error}" # required if no empty password
            # MYSQL_USER: "${DB_USER:?error}"
            # MYSQL_PASSWORD: "${DB_NAME:?error}"
        restart: unless-stopped
    adminer:
        image: adminer:4.8.1
        container_name: djs_adminer
        restart: unless-stopped
        ports:
            - 8002:8080 # 5432
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.com
            PGADMIN_DEFAULT_PASSWORD: test_password
    # webserver:
    #     image: nginx:latest
    #     container_name: webserver
    #     restart: unless-stopped
    #     tty: true
    #     ports:
    #     - "8003:80"
    #     - "8143:443"
    #     #    - 80:8080
    #     volumes:
    #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        
