version: "3.9"
services:
    backend:
        container_name: django_js_backend
        image: django_js:1.0.1
        build: .
        # tty: true
        ports:
            - 8001:8000
        volumes:
            - .:/home/django_js
        restart: unless-stopped
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
    db:
        image: postgres:15.1 # mysql:8.0.32
        container_name: djs_postgres_db
        volumes:
            - ./data/postgres/db:/var/lib/postgresql/data # - ./data/mysql/db:/var/lib/mysql
        environment:
            POSTGRES_DB: ${DB_NAME:?error} # abort if not set or empty
            POSTGRES_USER: ${DB_USER:?error}
            POSTGRES_PASSWORD: ${DB_PASSWORD?error} # abort if not set, proceed if empty ''
            # MYSQL_ALLOW_EMPTY_PASSWORD: "true" # not advised in prod only for testing
            # MYSQL_DATABASE: "${DB_NAME:?error}" # must set or error
            # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:?error}" # required if no empty password
            # MYSQL_USER: "${DB_USER:?error}"
            # MYSQL_PASSWORD: "${DB_NAME:?error}"
        restart: unless-stopped
        # adminer:
        #   image: adminer:4.8.1
        #   restart: unless-stopped
        #   ports:
        #     - 8082:5432 # 8080
        #   environment:
        #     PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
        #     PGADMIN_DEFAULT_PASSWORD: password
